icons_format = "{icon}"

[theme]
theme = "native"
[theme.overrides]
idle_fg = "#c0caf5"

[icons]
icons = "awesome6"

[icons.overrides]
backlight = "\uF185"

[[block]]
block = "focused_window"
format = " $title.str(max_w:48) |"
[block.theme_overrides]
idle_fg = "#27a1b9"

[[block]]
block = "music"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"

[[block]]
block = "sound"
step_width = 1
[[block.click]]
button = "left"
cmd = "helvum"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid|Wired} "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m/%d %I:%M %p') "
