source ~/.dotfiles/zsh/antigen.zsh

export NVM_COMPLETION=true
export NVM_AUTO_USE=true
export EDITOR=nvim

antigen use oh-my-zsh

antigen bundle git
antigen bundle lukechilds/zsh-nvm
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme denysdovhan/spaceship-prompt

antigen apply

alias w='curl wttr.in'
alias vi='nvim'
alias vim='nvim'
alias mutt='neomutt'
alias orphan='yay -Rns $(pacman -Qtdq)'
alias m='ncmpcpp'
alias img="kitty +kitten icat"

screenfetch -d "-gtk"

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null

export QT_QPA_PLATFORMTHEME='gnome'
