export EDITOR=nvim
export NVM_DIR=~/.nvm
export NVM_COMPLETION=true
export NVM_AUTO_USE=true
export GPG_TTY=$(tty)

alias w='curl wttr.in'
alias vi='nvim'
alias vim='nvim'
alias orphan='yay -Rns $(pacman -Qtdq)'
alias img="kitty +kitten icat"

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

pfetch

eval "$(starship init zsh)"
source /usr/share/nvm/init-nvm.sh
eval "$(pyenv init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
